name: Apply changes
on:
  push:
    branches:
      - main

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_DEPLOY_SA_KEY }}
          project_id: bjerk-core
          export_default_credentials: true
      - uses: pulumi/actions@v2
        env:
          PULUMI_ACCESS_TOKEN: ${{Â secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
        with:
          command: preview
          refresh: true
          stack-name: prod
          comment-on-pr: true
          github-token: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
